services:
  nginx:
    build: ./NGINX/
    networks:
      - inception

  MariaDB:
    build: ./MariaDB/
    volumes:
      - data_base:/var/lib/mysql
    networks:
      - inception
    secrets:
      - credentials

  WordPress:
    build: ./WordPress/
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception

volumes:
  data_base:
    name: data_base
    driver: local
    driver_opts:
      device: /home/jfikents/data/mysql
      o: bind
  wp_data:
    name: wp_data
    driver: local
    driver_opts:
      device: /home/jfikents/data/wordpress
      o: bind

networks:
  inception:
    name: inception
    driver: overlay

secrets:
  credentials:
    file: ./secrets/credentials.env