services:

  mariadb:
    build: ./requirements/MariaDB/
    volumes:
      - data_base:/var/lib/mysql
    networks:
      - inception
    secrets:
      - credentials
    restart: always

  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/WordPress/
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception
    restart: always
    environment:
      - DOMAIN_NAME=jfikents.42.fr
      - WP_TITLE=Inception

  nginx:
    depends_on:
      - wordpress
    build: ./requirements/NGINX/
    networks:
      - inception
    restart: always
    ports:
      - 443:443

volumes:
  data_base:
    name: data_base
    driver: local
    driver_opts:
      device: /home/jfikents/data/mysql
      o: bind
  wp_data:
    name: wp_data
    driver: local
    driver_opts:
      device: /home/jfikents/data/wordpress
      o: bind

networks:
  inception:
    name: inception
    driver: overlay

secrets:
  credentials:
    file: ../secrets/credentials.env